### PR TITLE
fixing a bug in which all handler retires executed within the same

### LINKED ISSUE #81: Transactions managed incorrectly between retries
Grabbit should create new transactions between retries of handlers in case of a failure of a handler.
Currently, all of the retries get executed within the same transaction.

### PR DESCRIPTION
**Pull request by rhinof**
transaction

When a handler fails and gets retried each retry should be run in a new
transaction

Closes #81

### CODE REVIEW

File: gbus/worker.go [hunk 1]
```diff
@@ -315,68 +315,44 @@ func (worker *worker) processMessage(delivery amqp.Delivery, isRPCreply bool) {
...
-				worker.span.LogFields(slog.Error(err))
-				worker.log().WithError(err).Error("failed committing transaction")
-				//if the commit failed we will reject the message
-				_ = worker.reject(false, delivery)
-			}
-		} else { /*if the bus in not transactional just try acking the message*/
-			_ = worker.ack(delivery)
-		}
-		//else there was an error in the invokation then try rollingback the transaction and reject the message
+		_ = worker.ack(delivery)
```
Comment (vladshub) [inline gbus/worker.go]: Why are you ignoring the error?

File: gbus/worker.go [hunk 2]
```diff
@@ -393,10 +369,23 @@ func (worker *worker) invokeHandlers(sctx context.Context, handlers []MessageHan
...
+			handlerErr := handler(ctx, message)
+			if handlerErr != nil {
+				hspan.LogFields(slog.Error(handlerErr))
+				if worker.isTxnl {
+					rbkErr := tx.Rollback()
+					if rbkErr != nil {
+						worker.log().WithError(rbkErr).Error("failed rolling back transaction when recovering from handler error")
+					}
+				}
+				return handlerErr
```
Comment (vladshub) [inline gbus/worker.go]: 🏆

File: gbus/worker.go (hunk 1 above)
Comment (rhinof) [reply gbus/worker.go]: after examining the code of worker.ack (and worker.nack) the retry strategy defined there retries the action until it succeeds (returns no error) in 100ms intervals

**Comment by vladshub** [comment]
image

File: gbus/worker.go (hunk 1 above)
Comment (vladshub) [reply gbus/worker.go]: then we should fix the function . not to return an error but it would be a whole different PR.

Comment (rhinof) [reply gbus/worker.go]: yes, will do it in a diff PR
