### PR TITLE
fix wrongly set correlation ids when sending a command

### LINKED ISSUE #219: Correlation Ids are wrongly set on outgoing commands
When a saga sends a command grabbit wrongly sets the saga correlation id on the outgoing saga.

Expected result: a command being sent by a saga via invocation.Bus().Send(...) should not contain a value in the SagaCorrelationID header.

Actual: the SagaCorrelationID header is set with the value of the SagaID

### PR DESCRIPTION
**Pull request by rhinof**
fixes #219

### CODE REVIEW

File: gbus/abstractions.go [hunk 1]
```diff
@@ -18,6 +18,8 @@ const (
 	CMD Semantics = "cmd"
 	//EVT represenst a messge with event semantics in grabbit
 	EVT Semantics = "evt"
+	//REPLY represenst a messge with reply semantics in grabbit
+	REPLY Semantics = "reply"
```
Comment (vladshub) [inline gbus/abstractions.go]: Are we sure that this is the correct place to add this sematic? since we are not using it anywhere except for the internal implementation of `setCorrelationId`....

Comment (rhinof) [reply gbus/abstractions.go]: I know, but it is worth making it explicit IMO
